### ISSUE TITLE
Release ibl-sort

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/ibl-sorter#13]
- [x] fix #14 
- [x] add generation of passingSpikes table to the computation of good units

- [x] release dependencies
  - [x] ibllib, branch iblsort
  - [x] iblscripts, branch iblsort
  - [x] iblsort, branch develop
  - [x] ibl-neuropixel >= 1.0.1
  - [x] slidingRefractory 1.1.1
  - [x] phylib 2.5.0

- [x] release as stand-alone
- [x] release on spike interface

Completion: the local servers are able to spike sort and register their data

**Comment by chris-langfield** [comment]
- [ ] Write a guide to setup pyks2 environment on linux server, update: https://docs.google.com/document/d/1CXjfEEtKkKw19xOnCjrqarLqdpyH4w4EmW-FzGFW8JM/edit
- [ ] saturation not output by `decompress_destripe_cbin`
- [ ] integration test on server

**Comment by chris-langfield** [comment]
Notes:

`pyfftw` install not covered by environment instructions
Have to change `cupy` to `cupy-cuda11x` in ibl-sorter requirements

**Comment by chris-langfield** [comment]
Error 1:

```
  File "/home/ibladmin/Documents/PYTHON/SPIKE_SORTING/ibl-sorter/.venv/lib/python3.10/site-packages/spikeinterface/core/binaryrecordingextractor.py", line 177, in __init__
    self.file = open(self.datfile, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ibladmin/scratch/pykilosort/.kilosort/imec_385_100s.ap/proc.dat'
```

**Comment by chris-langfield** [comment]
Tests have been cleaned up and all run (with GPU)

**Comment by oliche** [comment]
See specific issue for releasing with spike interface. Closing this for now.
